apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deploy
  namespace: nimesh-ns
  labels:
    app: fitness-app
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness-container
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-app-deploy-svc
  namespace: nimesh-ns
spec:
  selector:
    app: fitness
  ports:
    - port: 3001 # it is service port number we are using to expose the application to internet
      targetPort: 3000
      protocol: TCP
  type: ClusterIP