apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deploy
  namespace: nimesh-ns
  labels:
    app: fitness-app
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness-container
          image: muralisocial123/transaction-app:v1.0.0
          ports:
            - containerPort: 3000