apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deploy
  namespace: nimesh-ns
  labels:
    app: fitness-app
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness-container
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-app-deploy-svc
  namespace: nimesh-ns
spec:
  selector:
    app: fitness
  ports:
    - port: 3001 # it is service port number we are using to expose the application to internet
      targetPort: 5000
      protocol: TCP
  type: NodePort